### ISSUE TITLE
Add err message about insufficient funds when openchannel

### ISSUE THREAD

**Issue by raladev** [ConnextProject/rest-api-client#44] opened 2020-06-25 15:31 UTC
Steps:
0. ETH balance is 3 ETH
1. openchannel 4 ETH 

Actual Result:
[Screenshot from 2020-06-25 17-42-22](https://user-images.githubusercontent.com/29906866/85750009-01759980-b712-11ea-8e82-2bdfa3ee168a.png)

gas estimation err in connext logs + 500 error response to deposit call
```
[1593095894528] ERROR (71 on connext): Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":{"jsonrpc":"2.0","id":49,"error":{"code":-32000,"message":"insufficient funds for transfer"}},"error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x3b9aca00\",\"value\":\"0x68155a43676e0000\",\"from\":\"0x0a8cf804e45af6b8b1f6a3f66f33525dd8b98089\",\"to\":\"0x4a9a0389e892f9f62effc3d002aea761dc5a760b\"}],\"id\":49,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://eth.kilrau.com:52041"}, tx={"to":{},"value":{"_hex":"0x68155a43676e0000","_isBigNumber":true},"from":"0x0A8cf804e45aF6b8b1F6a3F66f33525dd8B98089","gasPrice":{},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.0.1)
    at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:179:21)
    at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:188:20)
    at /app/node_modules/@ethersproject/abstract-signer/lib/index.js:239:47
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Promise.all (index 5)
    Error: Error: cannot estimate gas; transaction may fail or may require manual gas limit (error={"reason":"processing response error","code":"SERVER_ERROR","body":{"jsonrpc":"2.0","id":49,"error":{"code":-32000,"message":"insufficient funds for transfer"}},"error":{"code":-32000},"requestBody":"{\"method\":\"eth_estimateGas\",\"params\":[{\"gasPrice\":\"0x3b9aca00\",\"value\":\"0x68155a43676e0000\",\"from\":\"0x0a8cf804e45af6b8b1f6a3f66f33525dd8b98089\",\"to\":\"0x4a9a0389e892f9f62effc3d002aea761dc5a760b\"}],\"id\":49,\"jsonrpc\":\"2.0\"}","requestMethod":"POST","url":"http://eth.kilrau.com:52041"}, tx={"to":{},"value":{"_hex":"0x68155a43676e0000","_isBigNumber":true},"from":"0x0A8cf804e45aF6b8b1F6a3F66f33525dd8B98089","gasPrice":{},"nonce":{},"gasLimit":{},"chainId":{}}, code=UNPREDICTABLE_GAS_LIMIT, version=abstract-signer/5.0.1)
        at Logger.makeError (/app/node_modules/@ethersproject/logger/lib/index.js:179:21)
        at Logger.throwError (/app/node_modules/@ethersproject/logger/lib/index.js:188:20)
        at /app/node_modules/@ethersproject/abstract-signer/lib/index.js:239:47
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
        at async Promise.all (index 5)
        at DepositController.<anonymous> (/app/node_modules/@connext/client/dist/controllers/DepositController.js:61:23)
        at Generator.throw (<anonymous>)
        at rejected (/app/node_modules/@connext/client/dist/controllers/DepositController.js:6:65)
        at runMicrotasks (<anonymous>)
        at processTicksAndRejections (internal/process/task_queues.js:97:5)
[1593095894531] INFO  (71 on connext): request completed
    reqId: 43
    url: "/deposit"
    statusCode: 500
```

Expected result:
insufficient funds error with proper error code and message

**Comment by kilrau** [comment] 2020-08-24 09:56
Duplicate of https://github.com/connext/rest-api-client/issues/23, can be closed @pedrouid @rhlsthrm

**Closed as completed** 2020-08-24 10:16 UTC
