### ISSUE TITLE
/withdraw does not work

### ISSUE THREAD

**Issue by ghost** [ConnextProject/rest-api-client#46] opened 2020-07-02 18:13 UTC
```
➜  rest-api-client git:(master) ✗ ./balance.sh
+ curl -H 'Content-Type: application/json' http://0.0.0.0:5040/balance/0x0000000000000000000000000000000000000000
+ jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100    89  100    89    0     0    198      0 --:--:-- --:--:-- --:--:--   198
{
  "freeBalanceOffChain": "9986000000000000000",
  "freeBalanceOnChain": "19999790000000000000"
}
➜  rest-api-client git:(master) ✗ ./withdraw.sh
+ curl -d '{"amount": "9986000000000000000"}' -H 'Content-Type: application/json' http://0.0.0.0:5040/withdraw
+ jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1448  100  1415  100    33  28300    660 --:--:-- --:--:-- --:--:-- 28960
{
  "message": "Error: no matching function (argument=\"name\", value=\"executeWithdraw\", code=INVALID_ARGUMENT, version=abi/5.0.1)\n    at Logger.makeError (/home/ar/rest-api-client/node_modules/@ethersproject/logger/lib/index.js:179:21)\n    at Logger.throwError (/home/ar/rest-api-client/node_modules/@ethersproject/logger/lib/index.js:188:20)\n    at Logger.throwArgumentError (/home/ar/rest-api-client/node_modules/@ethersproject/logger/lib/index.js:191:21)\n    at Interface.getFunction (/home/ar/rest-api-client/node_modules/@ethersproject/abi/lib/interface.js:176:24)\n    at Interface.encodeFunctionData (/home/ar/rest-api-client/node_modules/@ethersproject/abi/lib/interface.js:257:37)\n    at WithdrawCommitment.getTransactionDetails (/home/ar/rest-api-client/node_modules/@connext/apps/dist/index.js:304:85)\n    at WithdrawCommitment.encode (/home/ar/rest-api-client/node_modules/@connext/contracts/dist/src.ts/commitments/multisig-commitment.js:71:53)\n    at WithdrawCommitment.hashToSign (/home/ar/rest-api-client/node_modules/@connext/contracts/dist/src.ts/commitments/multisig-commitment.js:82:31)\n    at WithdrawalController.<anonymous> (/home/ar/rest-api-client/node_modules/@connext/client/dist/controllers/WithdrawalController.js:43:49)\n    at Generator.next (<anonymous>)\n    at fulfilled (/home/ar/rest-api-client/node_modules/@connext/client/dist/controllers/WithdrawalController.js:5:58)"
}
```

**Comment by ghost** [comment] 2020-07-02 18:14
This used to work with 6.7.4 client.

**Comment by aryabhuptani** [comment] 2020-07-06 15:37
Caused by a breaking change to the onchain fn for withdraw. We followed up in the chat about this so closing it for now.

We'll be much more careful about breaking changes now that we've gotten through this major update!

**Closed as completed by aryabhuptani** 2020-07-06 15:37 UTC
