### ISSUE TITLE
Client retries unlocking htlc up to dispute timeout

### ISSUE THREAD

**Issue by kilrau** [ConnextProject/rest-api-client#37] opened 2020-06-17 15:06 UTC
In order to enable https://github.com/connext/indra/issues/1254, the connext client has to automatically retry unlocking an htlc up to the dispute timeout. Currently it doesn't do that. xud tries to unlock an htlc via connext client exactly once. If that fails (which can be because of a temporary network issue) it gives up and the htlc remains locked practically resulting in loss of funds (even though htlc could be unlocked manually, but that's not really an option).

As a first urgent step the connext client should automatically retry to unlock an htlc off-chain up to the dispute timeout. That prevents temporary unlock failures from causing funds to disappear.

Second step is to automatically go on-chain after dispute timeout as described in https://github.com/connext/indra/issues/1254.

**Comment by aryabhuptani** [comment] 2020-06-22 10:05
I believe this is a duplicate of https://github.com/connext/indra/issues/1173, closing and will track it there

**Closed as completed by aryabhuptani** 2020-06-22 10:05 UTC
